"""
initial version

Revision ID: 650ba70468b9
Revises: 
Create Date: 2019-11-27 23:23:49.758323

"""
import microcosm_postgres
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650ba70468b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', microcosm_postgres.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', microcosm_postgres.models.UTCDateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_pet_tag'), 'pet', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_tag'), table_name='pet')
    op.drop_table('pet')
    # ### end Alembic commands ###
