image: python:3.8

cache:
  paths:
  - /root/.cache

stages:
  - build
  - docker_build_and_publish

build:
  stage: build
  script:
    - pip install tox setuptools qualifier
    - update_qualifier --no-use-git --branch-name "$CI_COMMIT_REF_NAME" --tag-name "$CI_COMMIT_TAG"
    - tox
    - QUALIFIER_VERSION=$(python setup.py --version)
    - echo "QUALIFIER_VERSION=$QUALIFIER_VERSION" >> dist/build.env
  artifacts:
    paths:
      - dist/

docker_build_and_publish:
  stage: docker_build_and_publish
  image: srikalyan/docker:stable
  services:
    - name: srikalyan/docker:stable-dind
      alias: docker
  script:
    - source dist/build.env
    - IMAGE_TAG="$CI_REGISTRY_IMAGE:$QUALIFIER_VERSION"
    - echo "The image tag is $IMAGE_TAG"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - build
